name: Jvm

on:
  create:
    branches: [ master ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Build files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: jvmTest
      - uses: eskatos/gradle-command-action@v1
        name: Publish Tag
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        with:
          arguments: publish -Pversion=$GITHUB_REF
        if: ${{ startsWith(github.ref, 'refs/tags') }}
      - uses: eskatos/gradle-command-action@v1
        name: Publish SNAPSHOT
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        with:
          arguments: publish
        if: ${{ startsWith(github.ref, 'refs/heads/master') }}